const ActionTypes = {
    SET_GLOBAL_STATS: 'SET_GLOBAL_STATS',
    SET_CRYPTOCOINS: 'SET_CRYPTOCOINS',
    SET_CRYPTONEWS: 'SET_CRYPTONEWS',
    SET_EXCAHNGES: 'SET_EXCHANGES',
    
    SET_COINS_DESCRIPTION: 'SET_COINS_DESCRIPTION',
    SET_CRYPTOCOIN_DETAIL: 'SET_CRYPTOCOIN_DETAIL',
    REMOVE_CRYPTOCOIN_DETAIL: 'SET_CRYPTOCOIN_DETAIL',
    SET_CRYPTOCOIN_PRICE_HISTORY: 'SET_CRYPTOCOIN_PRICEHISTORY',
    REMOVE_CRYPTOCOIN_PRICE_HISTORY: 'REMOVE_CRYPTOCOIN_PRICEHISTORY'
}

export default ActionTypes